site_name: scdataloader
theme: 
  name: readthedocs
  # analytics:
    # gtag: G-ABC123
site_url: https://www.jkobject.com/scdataloader/
nav:
  - Home: index.md
  - download and preprocess: notebooks/1_download_and_preprocess.ipynb
  - use the dataloader: notebooks/2_create_dataloader.ipynb
  - Dataset: Dataset.md
  - preprocess: preprocess.md
  - utils: utils.md
plugins: 
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            summary: true
            merge_init_into_class: true
            show_signature: false
      default_handler: python
  - git-revision-date-localized
  - git-authors
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: true
  

